sonar.projectKey=userkxm00_pos-global
sonar.organization=userkxm00
sonar.projectName=pos-global
sonar.sourceEncoding=UTF-8

sonar.sources=src,src-tauri
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/coverage/**,src-tauri/icons/**
sonar.rust.cargo.manifestPaths=src-tauri/Cargo.toml
sonar.rust.clippy.enabled=false
